apiVersion: v1
kind: Pod
metadata:
  name: test-app
  namespace: postman-insights-namespace
spec:
  containers:
    - name: nginx
      image: nginx:latest
      env:
        - name: POSTMAN_INSIGHTS_API_KEY
          value: "POSTMAN_INSIGHTS_API_KEY"
        - name: POSTMAN_INSIGHTS_PROJECT_ID
          value: "PROJECT_ID"
      ports:
        - containerPort: 80
