apiVersion: v1
kind: Pod
metadata:
  name: test-app
  namespace: postman-insights-namespace
spec:
  containers:
    - name: nginx
      image: nginx:latest
      env:
        - name: POSTMAN_INSIGHTS_API_KEY
          value: "YOUR_API_KEY_HERE"
        - name: POSTMAN_INSIGHTS_PROJECT_ID
          value: "YOUR_PROJECT_ID_HERE"
      ports:
        - containerPort: 80
